version: "3.8"

services:
  postgres:
    image: postgres #fetches form hub.docker.com
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"
